"""Out-of-sample evaluation: leave-one-maturity-out (LOMO) and leave-one-strike-out
(LOSO) cross-validation comparing the Dupire PINN against SVI, cubic-spline,
and Andreasen-Huge baselines.

Statistical inference:
  * Per-model RMSE / MAE with bootstrap CI; bootstrap respects fold structure
    (resample folds, not individual points).
  * Paired comparison via fold-level Diebold-Mariano-style test: for each
    fold compute mean |err_A| - |err_B|; one-sample t-test on the 9 fold-level
    differences. This properly accounts for within-fold dependence (every
    point in a fold is generated by the same trained model).
  * The naive point-level paired t-test is also reported for transparency.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import jax
import jax.numpy as jnp
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "analysis"))

from baselines import fit_svi, fit_spline  # noqa: E402
from baseline_ah import fit_ah  # noqa: E402
from train_pinn import build_normalizers, make_models, train, C_at  # noqa: E402

CLEAN_CSV = ROOT / "data" / "clean.csv"
OUT_DIR = ROOT / "data"
FIG_DIR = ROOT / "figures" / "cv"
FIG_DIR.mkdir(parents=True, exist_ok=True)

CV_PINN_NUM_ITER = 5_000
CV_PINN_N_COLLOC = 256
CV_SEED = 42
N_BOOT = 5_000


def predict_pinn(model, K_arr: np.ndarray, T_arr: np.ndarray, norm: dict) -> np.ndarray:
    c_net, _ = model
    K = jnp.asarray(K_arr, dtype=jnp.float32)
    T = jnp.asarray(T_arr, dtype=jnp.float32)
    return np.asarray(jax.vmap(lambda k, t: C_at(c_net, k, t, norm))(K, T))


# ----------------------------------------------------------------------
# LOMO
# ----------------------------------------------------------------------
def lomo_cv(df: pd.DataFrame) -> pd.DataFrame:
    Ts = sorted(df["T"].unique())
    print(f"LOMO CV: {len(Ts)} folds × (PINN + SVI + spline + AH)")
    rows = []
    t_overall = time.time()
    for fold_i, held_T in enumerate(Ts):
        train_df = df[df["T"] != held_T].reset_index(drop=True)
        test_df = df[df["T"] == held_T].reset_index(drop=True)
        n_test = len(test_df)
        print(f"\n[fold {fold_i+1}/{len(Ts)}] held T={held_T:.4f}  "
              f"train_n={len(train_df)}  test_n={n_test}")

        # PINN
        t0 = time.time()
        norm = build_normalizers(train_df)
        key = jax.random.PRNGKey(CV_SEED + fold_i)
        ki, kt = jax.random.split(key)
        model = make_models(ki)
        model, _ = train(model, train_df, norm, CV_PINN_NUM_ITER, kt,
                         n_colloc=CV_PINN_N_COLLOC, verbose=False)
        c_pinn = predict_pinn(model, test_df["K"].to_numpy(), test_df["T"].to_numpy(), norm)
        t_pinn = time.time() - t0

        # SVI
        t0 = time.time()
        svi = fit_svi(train_df)
        c_svi = svi.predict(test_df["K"].to_numpy(), test_df["T"].to_numpy())
        t_svi = time.time() - t0

        # Spline
        t0 = time.time()
        spline = fit_spline(train_df)
        c_spline = spline.predict(test_df["K"].to_numpy(), test_df["T"].to_numpy())
        t_spline = time.time() - t0

        # Andreasen-Huge
        t0 = time.time()
        ah = fit_ah(train_df)
        c_ah = ah.predict(test_df["K"].to_numpy(), test_df["T"].to_numpy())
        t_ah = time.time() - t0

        c_obs = test_df["call_equiv"].to_numpy()
        for i in range(n_test):
            rows.append({
                "fold": fold_i, "held_T": held_T,
                "K": float(test_df["K"].iloc[i]), "T": float(test_df["T"].iloc[i]),
                "C_obs": float(c_obs[i]),
                "C_pinn": float(c_pinn[i]), "C_svi": float(c_svi[i]),
                "C_spline": float(c_spline[i]), "C_ah": float(c_ah[i]),
                "resid_pinn": float(c_pinn[i] - c_obs[i]),
                "resid_svi": float(c_svi[i] - c_obs[i]),
                "resid_spline": float(c_spline[i] - c_obs[i]),
                "resid_ah": float(c_ah[i] - c_obs[i]),
            })
        print(f"  RMSE  pinn={np.sqrt(np.mean((c_pinn-c_obs)**2)):.4f}  "
              f"svi={np.sqrt(np.mean((c_svi-c_obs)**2)):.4f}  "
              f"spline={np.sqrt(np.mean((c_spline-c_obs)**2)):.4f}  "
              f"ah={np.sqrt(np.mean((c_ah-c_obs)**2)):.4f}  "
              f"(t: pinn={t_pinn:.0f}s svi={t_svi:.1f}s sp={t_spline:.2f}s ah={t_ah:.0f}s)")
    print(f"\ntotal LOMO time: {time.time() - t_overall:.0f}s")
    return pd.DataFrame(rows)


# ----------------------------------------------------------------------
# LOSO (within-maturity leave-one-strike-out for cheap-to-refit baselines)
# ----------------------------------------------------------------------
def loso_cv_baselines(df: pd.DataFrame) -> pd.DataFrame:
    """Within-maturity leave-one-strike-out for SVI and cubic spline (PINN
    excluded as it would require 192 retrainings; LOMO already covers PINN
    extrapolation in T). Spline needs >= 4 points so we skip slices with < 5
    observations."""
    rows = []
    for T in sorted(df["T"].unique()):
        slice_df = df[df["T"] == T].reset_index(drop=True)
        if len(slice_df) < 5:
            continue
        for hold_idx in range(len(slice_df)):
            train_slice = slice_df.drop(index=hold_idx).reset_index(drop=True)
            held = slice_df.iloc[hold_idx]
            full_train = pd.concat(
                [df[df["T"] != T], train_slice], ignore_index=True
            )
            try:
                svi = fit_svi(full_train)
                c_svi = float(svi.predict(np.array([held["K"]]), np.array([held["T"]]))[0])
            except Exception:
                c_svi = np.nan
            try:
                spline = fit_spline(full_train)
                c_spline = float(spline.predict(np.array([held["K"]]), np.array([held["T"]]))[0])
            except Exception:
                c_spline = np.nan
            rows.append({
                "T": float(T), "K": float(held["K"]),
                "C_obs": float(held["call_equiv"]),
                "C_svi": c_svi, "C_spline": c_spline,
                "resid_svi": float(c_svi - held["call_equiv"]) if not np.isnan(c_svi) else np.nan,
                "resid_spline": float(c_spline - held["call_equiv"]) if not np.isnan(c_spline) else np.nan,
            })
    return pd.DataFrame(rows)


# ----------------------------------------------------------------------
# Statistics with fold-respecting structure
# ----------------------------------------------------------------------
def block_bootstrap_metric(cv_df: pd.DataFrame, resid_col: str, n_boot: int = N_BOOT,
                           rng=None) -> dict:
    """Resample folds (with replacement), compute RMSE / MAE on the resampled
    aggregate. Respects within-fold dependence."""
    rng = rng or np.random.default_rng(0)
    folds = sorted(cv_df["fold"].unique())
    n_folds = len(folds)
    fold_to_resid = {f: cv_df[cv_df["fold"] == f][resid_col].to_numpy() for f in folds}
    rmse_boot = np.empty(n_boot); mae_boot = np.empty(n_boot)
    for b in range(n_boot):
        sampled = rng.choice(folds, size=n_folds, replace=True)
        all_resid = np.concatenate([fold_to_resid[f] for f in sampled])
        rmse_boot[b] = np.sqrt(np.mean(all_resid ** 2))
        mae_boot[b] = np.mean(np.abs(all_resid))
    full_resid = cv_df[resid_col].to_numpy()
    return {
        "rmse": float(np.sqrt(np.mean(full_resid ** 2))),
        "rmse_ci95": [float(np.percentile(rmse_boot, 2.5)),
                      float(np.percentile(rmse_boot, 97.5))],
        "mae": float(np.mean(np.abs(full_resid))),
        "mae_ci95": [float(np.percentile(mae_boot, 2.5)),
                     float(np.percentile(mae_boot, 97.5))],
        "max_abs_err": float(np.max(np.abs(full_resid))),
        "n_points": int(len(full_resid)),
        "n_folds": int(n_folds),
    }


def fold_level_paired_test(cv_df: pd.DataFrame, col_a: str, col_b: str,
                           label: str) -> dict:
    """Paired t-test on per-fold mean |err|. Each fold is one observation; the
    test has n_folds (= 9) degrees of freedom and properly accounts for the
    fact that within-fold predictions are not independent."""
    fold_diffs = []
    for f in sorted(cv_df["fold"].unique()):
        sub = cv_df[cv_df["fold"] == f]
        d = float(np.mean(np.abs(sub[col_a])) - np.mean(np.abs(sub[col_b])))
        fold_diffs.append(d)
    fold_diffs = np.array(fold_diffs)
    t_stat, p_val = stats.ttest_1samp(fold_diffs, 0.0)
    return {
        "comparison": label,
        "n_folds": len(fold_diffs),
        "mean_fold_diff": float(np.mean(fold_diffs)),
        "std_fold_diff": float(np.std(fold_diffs, ddof=1)),
        "t": float(t_stat),
        "p": float(p_val),
        "naive_t_point_level": float(stats.ttest_1samp(
            np.abs(cv_df[col_a].to_numpy()) - np.abs(cv_df[col_b].to_numpy()), 0.0
        ).statistic),
        "naive_p_point_level": float(stats.ttest_1samp(
            np.abs(cv_df[col_a].to_numpy()) - np.abs(cv_df[col_b].to_numpy()), 0.0
        ).pvalue),
        "interpretation": (
            "A wins (|err_A| < |err_B| significant)" if (np.mean(fold_diffs) < 0 and p_val < 0.05)
            else "B wins (|err_B| < |err_A| significant)" if (np.mean(fold_diffs) > 0 and p_val < 0.05)
            else "no significant difference at fold level"
        ),
    }


def aggregate(cv_df: pd.DataFrame) -> dict:
    rng = np.random.default_rng(0)
    summary = {
        "models": {
            m: block_bootstrap_metric(cv_df, f"resid_{m}", rng=rng)
            for m in ["pinn", "svi", "spline", "ah"]
        },
        "paired_tests_fold_level": [
            fold_level_paired_test(cv_df, "resid_pinn", "resid_svi", "pinn vs svi"),
            fold_level_paired_test(cv_df, "resid_pinn", "resid_spline", "pinn vs spline"),
            fold_level_paired_test(cv_df, "resid_pinn", "resid_ah", "pinn vs ah"),
            fold_level_paired_test(cv_df, "resid_ah", "resid_svi", "ah vs svi"),
        ],
        "per_fold_rmse": (
            cv_df.groupby("held_T")
                 .apply(lambda g: {
                     "n": int(len(g)),
                     "pinn": float(np.sqrt(np.mean(g["resid_pinn"] ** 2))),
                     "svi": float(np.sqrt(np.mean(g["resid_svi"] ** 2))),
                     "spline": float(np.sqrt(np.mean(g["resid_spline"] ** 2))),
                     "ah": float(np.sqrt(np.mean(g["resid_ah"] ** 2))),
                 }, include_groups=False)
                 .to_dict()
        ),
    }
    return summary


def aggregate_loso(loso_df: pd.DataFrame) -> dict:
    out = {}
    for m in ["svi", "spline"]:
        sub = loso_df.dropna(subset=[f"resid_{m}"])
        resid = sub[f"resid_{m}"].to_numpy()
        out[m] = {
            "rmse": float(np.sqrt(np.mean(resid ** 2))),
            "mae": float(np.mean(np.abs(resid))),
            "max_abs_err": float(np.max(np.abs(resid))),
            "n": int(len(resid)),
        }
    return out


# ----------------------------------------------------------------------
# Plots
# ----------------------------------------------------------------------
def plot_results(cv_df: pd.DataFrame, summary: dict, S: float) -> None:
    fig, axes = plt.subplots(1, 4, figsize=(20, 5), sharey=True)
    titles = ["PINN", "SVI", "spline", "Andreasen-Huge"]
    cols = ["resid_pinn", "resid_svi", "resid_spline", "resid_ah"]
    keys = ["pinn", "svi", "spline", "ah"]
    vmax = float(np.max(np.abs(cv_df[cols].to_numpy())))
    for ax, title, col, key in zip(axes, titles, cols, keys):
        sc = ax.scatter(cv_df["K"] / S, cv_df["T"], c=cv_df[col],
                        cmap="coolwarm", vmin=-vmax, vmax=vmax, s=30)
        ax.set_xlabel("K/S")
        ax.set_title(f"{title}\nRMSE={summary['models'][key]['rmse']:.3f}")
    axes[0].set_ylabel("T (held out)")
    plt.colorbar(sc, ax=axes, label="residual ($)")
    fig.suptitle("LOMO out-of-sample residuals (held-out maturity per fold)")
    plt.savefig(FIG_DIR / "lomo_residuals.png", dpi=600, bbox_inches="tight")
    plt.close()

    fig, ax = plt.subplots(figsize=(12, 5))
    Ts = sorted(summary["per_fold_rmse"].keys())
    x = np.arange(len(Ts))
    width = 0.20
    for offset, key, color in [
        (-1.5*width, "pinn", "C0"), (-0.5*width, "svi", "C1"),
        (0.5*width, "spline", "C2"), (1.5*width, "ah", "C3"),
    ]:
        vals = [summary["per_fold_rmse"][T][key] for T in Ts]
        ax.bar(x + offset, vals, width, label=key.upper())
    ax.set_xticks(x)
    ax.set_xticklabels([f"{T:.3f}" for T in Ts], rotation=30)
    ax.set_xlabel("held-out maturity T")
    ax.set_ylabel("RMSE on held-out points ($)")
    ax.set_title("Per-fold out-of-sample RMSE")
    ax.legend()
    plt.tight_layout()
    plt.savefig(FIG_DIR / "lomo_rmse_per_fold.png", dpi=600)
    plt.close()


def main() -> None:
    df = pd.read_csv(CLEAN_CSV)
    cv_df = lomo_cv(df)
    cv_df.to_csv(OUT_DIR / "cv_predictions.csv", index=False)
    print(f"\nsaved: {OUT_DIR / 'cv_predictions.csv'}")

    print("\nLOSO (within-maturity) for SVI and spline ...")
    loso_df = loso_cv_baselines(df)
    loso_df.to_csv(OUT_DIR / "loso_predictions.csv", index=False)

    summary = aggregate(cv_df)
    summary["loso_baselines"] = aggregate_loso(loso_df)
    with open(OUT_DIR / "cv_summary.json", "w") as f:
        json.dump(summary, f, indent=2, default=lambda o: float(o) if hasattr(o, "__float__") else o)
    print(f"saved: {OUT_DIR / 'cv_summary.json'}")

    print("\n=== LOMO aggregate (fold-bootstrap CI) ===")
    for name, m in summary["models"].items():
        print(f"  {name:7s} RMSE={m['rmse']:.4f}  CI95=[{m['rmse_ci95'][0]:.4f}, {m['rmse_ci95'][1]:.4f}]  "
              f"MAE={m['mae']:.4f}  max|err|={m['max_abs_err']:.4f}")

    print("\n=== Fold-level paired tests (n_folds = 9) ===")
    print("  comparison              fold_diff      t        p       naive_t   naive_p   verdict")
    for pt in summary["paired_tests_fold_level"]:
        print(f"  {pt['comparison']:18s}  {pt['mean_fold_diff']:+.4f}  "
              f"{pt['t']:+.3f}  {pt['p']:.4f}  "
              f"{pt['naive_t_point_level']:+.3f}  {pt['naive_p_point_level']:.4f}  "
              f"{pt['interpretation']}")

    print("\n=== LOSO baselines (in-maturity strike-out) ===")
    for m, info in summary["loso_baselines"].items():
        print(f"  {m:7s} RMSE={info['rmse']:.4f}  MAE={info['mae']:.4f}  n={info['n']}")

    S = float(df["S"].iloc[0])
    plot_results(cv_df, summary, S)
    print(f"saved: {FIG_DIR}/*.png")


if __name__ == "__main__":
    main()
